docs_dir: src
site_url: https://bloom.sh/the-guide
repo_url: https://gitlab.com/bloom42/bloom
edit_uri: https://gitlab.com/bloom42/bloom/tree/master/the_guide/src/
site_dir: dist/

use_directory_urls: false

theme:
  custom_dir: 'themes/material'
  name: null
  logo: 'assets/icon.png'
  language: en
  feature:
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: 'blue'
    accent: 'blue'

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

site_name: The Guide


nav:
  - Introduction: index.md

  - Organization:
    - Vision: organization/vision.md
    - Mission: organization/mission.md
    - Values: organization/values.md
    - Structure: organization/structure.md
    - Leadership: organization/leadership.md
    - Workflow: organization/workflow.md
    - Roadmap: organization/roadmap.md
    - Contributing: organization/contributing.md
    - Social media: organization/social_media.md

  - Projects:
    # - Overview: projects/index.md
    - Authenticator: projects/authenticator/index.md
    - Bloom:
      - Overview: projects/bloom/index.md
      - Development: projects/bloom/development.md
      - Architecture: projects/bloom/architecture.md
      - Security:
        - Overview: projects/bloom/security/overview.md
        - Authentication: projects/bloom/security/authentication.md
        - Chat: projects/bloom/security/chat.md
        - Drive: projects/bloom/security/drive.md
        - Calendar: projects/bloom/security/calendar.md
      - Design: projects/bloom/design.md
      - API: projects/bloom/api.md
      - Self hosting: projects/bloom/self_hosting.md
      - Status page: projects/bloom/status_page.md
      - Website: projects/bloom/website.md
      - Billing: projects/bloom/billing.md
      - Bitflow: projects/bloom/bitflow.md
      - Calculator: projects/bloom/calculator.md
      - Calendar: projects/bloom/calendar.md
      - Chat: projects/bloom/chat.md
      - Contacts: projects/bloom/contacts.md
      - Discover: projects/bloom/discover.md
      - Drive: projects/bloom/drive.md
      - Gallery: projects/bloom/gallery.md
      - Groups: projects/bloom/groups.md
      - Music: projects/bloom/music.md
      - MyAccount: projects/bloom/myaccount.md
      - Notes: projects/bloom/notes.md
      - Phaser: projects/bloom/phaser.md
      - Platform: projects/bloom/platform.md

    - crypto42: projects/crypto42/index.md

    - SANE: projects/sane/index.md

  - Engineering:
    - Tao: engineering/tao.md
    - Setup: engineering/setup.md
    - Cryptography: engineering/cryptography.md
    - Mobile: engineering/mobile.md
    - Qt: engineering/qt.md
    - Languages:
      - Rust: engineering/languages/rust.md
      - TypeScript: engineering/languages/typescript.md
      - Vue: engineering/languages/vue.md
      - JavaScript: engineering/languages/javascript.md
      - Elixir: engineering/languages/elixir.md
      - Go: engineering/languages/go.md
    - Patterns:
      - Event Sourcing: engineering/patterns/event_sourcing.md
      - Flux: engineering/patterns/flux.md
    - Templates:
      - Git: engineering/templates/git.md
      - GitLab:
        - Issues: engineering/templates/gitlab/issues.md
        - Merge requests: engineering/templates/gitlab/merge_requests.md
      - Editor Config: engineering/templates/editor_config.md
      - Vue: engineering/templates/vue.md
      - Docker: engineering/templates/docker.md
      - ESLint: engineering/templates/eslint.md
      - TypeScript: engineering/templates/typescript.md
      - bable: engineering/templates/babel.md
      - SCSS: engineering/templates/scss.md
    - Licenses:
      - Overview: engineering/licenses/overview.md
      - Apache 2.0: engineering/licenses/apache_2.0.md

  - People Operations: people_operations/index.md

  - Marketing: marketing/index.md

  - Sales: sales/index.md

  - Finance: finance/index.md

  - Legal: legal/index.md
