[package]
name = "bloom_const"
version = "0.1.0"
authors = ["z0mbie42 <sylvain@kerkour.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto42 = { version = "0.5", git = "https://gitlab.com/bloom42/libs/crypto42-rs" }
